# Generated by Django 5.0.1 on 2024-01-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kontak', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('seminar', 'Seminar'), ('to', 'Try Out'), ('bundle', 'Bundling')], max_length=50)),
                ('tf', models.ImageField(upload_to='static/proof_image/')),
                ('used', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
