# Generated by Django 5.0.1 on 2024-01-06 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(default='None', max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('kontak', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('Seminar', 'Seminar'), ('Try Out', 'Try Out'), ('Bundle 1', 'Bundling 1'), ('Bundle 2', 'Bundling 2')], max_length=50)),
                ('nama2', models.CharField(max_length=255)),
                ('kontak2', models.CharField(max_length=255)),
                ('tf', models.ImageField(upload_to='static/proof_image/')),
                ('used', models.CharField(default='No', max_length=10)),
                ('note', models.TextField(default='-')),
                ('status', models.TextField(default='Tunggu Konfirmasi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
