# Generated by Django 5.0.1 on 2024-01-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsubmission',
            name='tf',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
