# Generated by Django 5.0.1 on 2024-01-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticketsubmission_tf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsubmission',
            name='tf',
            field=models.ImageField(upload_to='root/Project/Formakara/static/images/'),
        ),
    ]
