# Generated by Django 5.0.1 on 2024-01-08 07:15

import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketsubmission_tf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsubmission',
            name='username',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketsubmission',
            name='username2',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketsubmission',
            name='tf',
            field=models.ImageField(upload_to=ticket.models.upload_to),
        ),
    ]
